### ISSUE TITLE
Relax the forced load order for resources used in join step?

### ISSUE THREAD

**Issue by adyork** [BCODMO/frictionless-usecases#11]
I keep running into the error that tells you you have to load the "source" before the "target" if you are using a join step.  @BCODMO/frictionlessdata-pilot-project , @lwinfree  is there any way you can relax the load order requirement for join?

e.g.
> | AssertionError: Source resource (event_log) must appear before target resource (nutrients), found: ['nutrients', 'event_log']

This is because the natural order when developing a pipeline for us is that we load the main dataset (e.g. nutrient data) we are trying to process first which will become the "target" of the join eventually.  At this point I may not even know I need a join step so wouldn't even think to load some other data before this.

Then we look at that data and notice that say it is missing the station numbers or something we can get from another data source.  So then we add another load step to load the event log.

I add a join step with the target as the main dataset I am trying to process, the nutrient data.  And the "source" is the event log.

I run the pipeline and get an error:

```
INFO :RESULTS:

INFO :FAILURE: ./6fb428f0-6838-11e9-a7e3-0242ac110002/IVARS_elementa-aggregate

ERROR log from processor join:

+--------

| Traceback (most recent call last):

| File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/join.py", line 32, in <module>

| spew_flow(flow(ctx.parameters), ctx)

| File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/utilities/flow_utils.py", line 46, in spew_flow

| datastream = flow.datastream()

| File "/usr/local/lib/python3.6/site-packages/dataflows/base/flow.py", line 18, in datastream

| return self._chain(ds)._process()

| File "/usr/local/lib/python3.6/site-packages/dataflows/base/datastream_processor.py", line 72, in _process

| datastream = self.source._process()

| File "/usr/local/lib/python3.6/site-packages/dataflows/base/datastream_processor.py", line 75, in _process

| self.datapackage = self.process_datapackage(self.datapackage)

| File "/usr/local/lib/python3.6/site-packages/dataflows/helpers/datapackage_processor.py", line 15, in process_datapackage

| ret = next(self.dp_processor)

| File "/usr/local/lib/python3.6/site-packages/dataflows/processors/join.py", line 309, in func

| process_datapackage(package.pkg.descriptor)

| File "/usr/local/lib/python3.6/site-packages/dataflows/processors/join.py", line 299, in process_datapackage

| .format(source_name, target_name, resource_names)

| AssertionError: Source resource (event_log) must appear before target resource (nutrients), found: ['nutrients', 'event_log']

+--------
```

**Comment by roll** [comment]
@adyork 
Unfortunately, it's not possible because of internal architecture of `datapackage-pipilines`. It processes data in a stream and it needs a source resource to come first to the `join` step for creating an index.

Hopefully it's a minor inconvenience because it's always possible just to move the source load step before the target load step in a DPP spec.

**Comment by adyork** [comment]
Thanks for the explanation. It was worth asking the question.  I suppose we can tool around the inconvenience to more easily re-order the steps.
