### ISSUE TITLE
Number type incorrect precision when passed a float

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#13]
OK, so this will be somewhat hard to explain because my only examples come from custom processors or custom parsers that we've built. If you want, I can give you an example with a custom processor over at https://github.com/BCODMO/bcodmo_processors, but I also plan to update these processors to get around this issues ASAP. Therefore this is also low priority, but I do think it is a bug on your end and I think I have a way to fix it.

The issue is when values are cast to the `number` type. Specifically, this line [right here](https://github.com/frictionlessdata/tableschema-py/blob/master/tableschema/types/number.py#L28). There are four cases to look at.

- If the value is already type Decimal, it will just return the value and never get here 

:heavy_check_mark: 
- If the value is type string, it will convert a string val to a Decimal using Decimal(val)
```
>>> from decimal import Decimal
>>> test = '24.122667'
>>> Decimal(test)
Decimal('24.122667')
```
:heavy_check_mark: 

- If the value is within six.integer_types, it will convert the integer to Decimal:
```
>>> from decimal import Decimal
>>> test = 24
>>> Decimal(test)
Decimal('24')
```

:heavy_check_mark: 

- The last case, if the value is a float, it will convert a float to Decimal, which has precision problems.

```
>>> from decimal import Decimal
>>> test = 24.122667
>>> Decimal(test)
Decimal('24.12266699999999985948306857608258724212646484375')
```
:x: 

Once again, sorry I don't have an actual pipeline-spec.yaml you could run to see this, but I think it's a problem that if floats are passed into this function you get a totally unexpected value. The easy solution is to change the line I linked to
```
value = Decimal(str(value))
```
converting the value to a string before passing into Decimal.

**Comment by lwinfree** [comment]
@cschloer Is this fixed in the PR above? Or should Evgeny still look into this? Thx!

**Comment by cschloer** [comment]
Hey, so I pushed a fix in our code that works around this bug, but I decided to post this issue anyways because I think it is a bug in frictionless. It is low priority on our end because of the fix.

**Comment by roll** [comment]
Fixed in:
```
pip install --upgrade tableschema=1.5.4
```

**Comment by cschloer** [comment]
Sweet! Thanks for the fix. FYI I'm traveling for the next 4 or so weeks, so you might get some slower responses from me.
