### ISSUE TITLE
Can't rename a field if there are two with same name?

### ISSUE THREAD

**Issue by adyork** [BCODMO/frictionless-usecases#15]
Pipeline tool version: 3c33d72
Browser: firefox version 66.0.0
OS: Linux
______________________________

[pipeline-spec.yaml.754685.txt](https://github.com/BCODMO/pipeline-web/files/3204195/pipeline-spec.yaml.754685.txt)

Describe the expected behavior here:
If you select the first occurrence in the list, that is the one that changes.   The other remains the same.

Describe the actual behavior here:
I get an error if I try to change the name of a column that has two identical named fields.  There are two named "Pnet N".  Trying to change the first to Gnet_N and second to Pnet_N.
```

INFO :RESULTS:

INFO :FAILURE: ./b15f62ba-7bfc-11e9-b037-0242ac110002/754685_Carpenter2018_hourly-metabolism

ERROR log from processor bcodmo_pipeline_processors.rename_fields:

+--------

| Traceback (most recent call last):

| File "/usr/local/lib/python3.6/site-packages/bcodmo_processors/bcodmo_pipeline_processors/rename_fields.py", line 53, in <module>

| spew(modify_datapackage(datapackage), process_resources(resource_iterator))

| File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 73, in spew

| for rec in res:

| File "/usr/local/lib/python3.6/site-packages/bcodmo_processors/bcodmo_pipeline_processors/rename_fields.py", line 38, in process_resource

| value = row[old_field_name]

| File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/utilities/lazy_dict.py", line 32, in __getitem__

| return self._inner.__getitem__(item)

| KeyError: 'Pnet N'
```

**Comment by cschloer** [comment]
@roll So we've run into a bit of a problem here. Sometimes we are submitted datasets that have multiple columns with the same name.

My workaround idea is to add an option to load that automatically adds a `(1)`, `(2)`, etc. to the end of a repeated column name similar to how files are downloaded files are handled in an OS. This would (I think) mean updating all of the parsers provided by dataflows. Would this functionality be something you would be willing to implement?

**Comment by roll** [comment]
@cschloer 
I think the `load` option makes sense 

cc @akariv

**Comment by roll** [comment]
It's been merged to `dataflows-py` and will be released I think as `dataflows@0.0.58` shortly.

The API is to achieve the result we have discussed (adding suffixes to duplicate headers):

```duplicate:
  title: duplicate
  description: "duplicate headers"
  pipeline:

  - run: load
    parameters:
      from: 'duplicate.csv'
      name: duplicate
      format: csv
      deduplicate_headers: true

  - run: dump.to_path
    parameters:
      resources: [duplicate]
      out-path: 'output'
      pretty-descriptor: true
```

**Comment by roll** [comment]
Hi @akariv could you please release `dataflows@0.0.58`?

**Comment by roll** [comment]
@cschloer 
It's on PyPi)

**Comment by cschloer** [comment]
Thank you!
