### ISSUE TITLE
Can't import csv file - bracket issues?

### ISSUE THREAD

**Issue by adyork** [BCODMO/frictionless-usecases#20]
Can't load source file: https://raw.githubusercontent.com/BCODMO/frictionless-usecases/master/usecases/699169_Doliolid-CTD/orig/CTD%20DOLDIET004_JAN2016_CAST001.csv
* Added this file and 19 others in usecase [699169_Doliolid-CTD](https://github.com/BCODMO/frictionless-usecases/tree/master/usecases/699169_Doliolid-CTD)

data file looks like this:
![image](https://user-images.githubusercontent.com/9537357/58506741-1c1bbe80-815e-11e9-9e91-945d203da61a.png)

Tried doing skip rows with nothing "*" and "\*" but all same result.  I don't think that is the problem since the Voltage column value 1 is in 1st row.
![image](https://user-images.githubusercontent.com/9537357/58506649-e1b22180-815d-11e9-89ce-799880a6c077.png)

@cschloer you had some thoughts about the brackets being an issue, can you elaborate?

**Comment by cschloer** [comment]
No thoughts other than if you change the brackets in the column names to parentheses (or remove them entirely) the data loads properly for that field. So it's an issue with a field name having a bracket. Maybe another regex problem?

**Comment by roll** [comment]
Thanks. It's a `tabulator` problem - https://github.com/frictionlessdata/tabulator-py/issues/264. I'm working on resolving it.

**Comment by adyork** [comment]
Great! That will really help.  It is extremely common for our data submitters to include units in the column name in brackets.

**Comment by roll** [comment]
It's fixed now with:
```bash
pip install --upgrade tabulator==1.22
```

**Comment by adyork** [comment]
Excellent! Thanks for the quick action.
