### ISSUE TITLE
Standard processor sort does not take into account types

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#21]
Hi,

If you use the sort standard processor with a single field as the sort-by key, that field's type is not taken into account. That means there is no way to sort a resource by a number field or a datetime field.

One solution would be to change how the sort key is inputted to the sort processor. Currently you input a string with format brackets (`{}`)  for field names. I think it would be make sense to instead take in a list of fields. For each row, the first field in the list is compared (taking into account type), with ties being broken by subsequent rows in the input list.

**Comment by roll** [comment]
Fixed in `dataflows@0.62`

**Comment by cschloer** [comment]
Works well! Thanks!
