### ISSUE TITLE
Pipeline dashboad/status badges enhancement

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#24]
Hi,

I'm working on a feature for our tool that will allow a pipeline to be run in the background. This is especially useful for very large datasets that take 40+ minutes to complete.

I would like to use the Pipeline Status Dashboard tool to show status updates on the running pipeline. I have a few questions and/or enhancement requests.

I run `dpp init` and `dpp serve`. The pipeline status dashboard correctly shows no pipelines. However, when I then run a single pipeline (using `dpp run ./8f0b1d04-c813-11e9-97a3-6057181bb7cd/date`), the status pages shows this:
![Screenshot from 2019-08-27 12-43-26](https://user-images.githubusercontent.com/7134143/63790907-49484c00-c8c8-11e9-9572-7f72f45e3038.png)

The second pipeline is the one I just ran. My questions are:

1. Where did the first pipeline come from and what is it?
2. Why does the second pipeline not show any success status or last run time? Is that only available if it is running on a schedule? This is particularly confounding because if I go to the badge endpoint for this pipeline (`http://0.0.0.0:5000/badge/8f0b1d04-c813-11e9-97a3-6057181bb7cd/date`) it correctly shows success:
![Screenshot from 2019-08-27 12-48-32](https://user-images.githubusercontent.com/7134143/63791217-033fb800-c8c9-11e9-9b2b-b853383d13eb.png)

3. When I go to the PipelineStatus endpoint for my particular pipeline (either `http://0.0.0.0:5000/PipelineStatus:./8f0b1d04-c813-11e9-97a3-6057181bb7cd`, which is what the link on the left goes to, or `http://0.0.0.0:5000/PipelineStatus:./8f0b1d04-c813-11e9-97a3-6057181bb7cd/date` which is what I suspect is correct) I get a page with 0 pipelines. How can I see a detail page (not a badge page) for an individual pipeline?

Feature requests:

1. It would be great if the badge endpoint could show the date last run
2. If I was correct above and the status on the main dashboard page is only available for pipelines running on a schedule, can that be changed to include pipelines run not on a schedule?

Thank you for reading through all of this!

**Comment by roll** [comment]
@cschloer 
I also didn't find any timestamp to add a date to the badge. And not sure about these two tasks instead of one (cc @akariv)

BTW don't you consider using shields.io directly in your code. If you have enough data to create it. It can make it less coupled with DPP e.g.:

https://img.shields.io/badge/pipeline-succeeded_2019_01_01-brightgreen.svg

**Comment by cschloer** [comment]
Sorry I don't think I understand what you mean about two tasks instead of one?

The badge feature request is somewhat secondary, I"m just hoping to use this already built PipelineStatus enpdoint for my uses! I can totally build my own badge-type thing, or just display the status as text.

**Comment by roll** [comment]
@cschloer 
> Where did the first pipeline come from and what is it?
I meant two pipelines instead of one. I also not sure what it is.

> The badge feature request is somewhat secondary
Sorry, Conrad, what is the primary request in this issue? It says `Pipeline dashboad/status badges enhancement` so I'm a little bit lost :smiley:

**Comment by cschloer** [comment]
Sorry for being confusing! I think the primary request is having a pipeline that is run through `dpp run` show up on the Pipeline Status page as completed, running, error, etc. Currently, as described above, it shows `Last run triggered: None` a bunch of times.

**Comment by roll** [comment]
@cschloer 
Should be fixed in dpp@2.1.10

Please re-open if not
