### ISSUE TITLE
Issue with Infer Strategy/Cast Strategy and xlsx files

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#27]
Hi @roll . We are having issues with xlsx files and the `infer_strategy` and `cast_strategy` parameters.

Here is the dataset: https://datadocs.bco-dmo.org/data/302/TestProject/data/round-test2.xlsx

Running the pipeline with `infer_strategy: full, cast_strategy: schema` works fine. However, if you do `infer_strategy: strings, cast_strategy: schema` there is a cast error:
```
Field "DateTime custom ISO" can't cast value "2017-04-19 15:17:00.000004" for type "string" with format "default"
```
Why can't a field be cast to a string when it is being inferred as a string? Isn't that the easiest cast to do? This error also happens when cast_strategy is "Do nothing", but it happens instead in the dump_to_path step. The only way to not make it error is have the parameter set to  `infer_strategy: strings, cast_strategy: strings`. Are we misunderstanding how these parameters work? The weird thing is that this error does not happen when the file is a csv, so I'm assuming the load processor is somehow taking into account the type that is stored within th excel file?

**Comment by roll** [comment]
Thanks, I'll investigate

**Comment by roll** [comment]
@cschloer 
I have proposed a PR to `dataflows` to resolve this issue - https://github.com/datahq/dataflows/pull/115

As a quick fix, you can use the tabulator's `force_strings` parameter:

```python
from pprint import pprint
from dataflows import Flow, load

flow = Flow(
    load(
        'https://datadocs.bco-dmo.org/data/302/TestProject/data/round-test2.xlsx',
        infer_strategy='strings',
        cast_strategy='schema',
        force_strings=True,
    ),
)
pprint(flow.results()[0])
pprint('---')
pprint(flow.results()[1].descriptor)
```

**Comment by cschloer** [comment]
Great thanks! So it seems like it wasn't actually specific to excel?

**Comment by roll** [comment]
No, e.g. json is also affected
