### ISSUE TITLE
Hash & Filesize not saved in datapackage at a resource level

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#28]
It seems like the `counters` parameter in `dump_to_path` is not working for resource specific metadata like hash and filesize. When `counters: resource-hash` is set (or if it's left alone, as it by default `hash`) the resulting datapackage does not have a hash.

I played around a bit with the code and found that [this line](https://github.com/datahq/dataflows/blob/master/dataflows/processors/dumpers/file_dumper.py#L92) properly sets the hash parameter, but outside of the rows_processor function that updated value does not stick. 

@roll @akariv

**Comment by roll** [comment]
@cschloer 
Thanks. I'll investigate

**Comment by roll** [comment]
The fix is here - https://github.com/datahq/dataflows/pull/118
