### ISSUE TITLE
Feature request: regular expression skip rows

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#34]
Currently the skip_rows parameter takes in a list of strings and numbers, skipping the rows that correspond with the number and a row if it starts with that string.

Can we add a new skip_rows_regex parameter that takes in a list of strings (regular expressions) such that if any of the regular expressions pass, the row will be skipped.

**Comment by roll** [comment]
To be handled in https://github.com/frictionlessdata/tabulator-py/pull/290
