### ISSUE TITLE
Bug? in tabulator headers parameter

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#35]
We're confused by a behavior of tabulator when parsing multiple rows as header rows.

https://github.com/frictionlessdata/tabulator-py/blob/master/tabulator/stream.py#L607

The line above is an if statement that only adds the value of the row to the header if the value inside that row is not equal to the end of the header that has up to then been generated.

We have an excel sheet with 4 rows to be used as headers.
![Screenshot from 2020-01-06 13-53-12](https://user-images.githubusercontent.com/7134143/71819337-e80d6200-308b-11ea-8080-146cdf40b8d5.png)

The expected header value would be `135 C 182 2` but because 182 ends in 2, the 2 is truncated and the resulting header is `135 C 182`. 

Can we either change this behavior or add a flag to tabulator that will overwrite this behavior?

Thanks!

A basic csv to test this would be:
```
1
1
abc
def
ghi
```

Load as csv, set the header rows to 1 and 2, expected header `1 1` but end up seeing just `1`.

**Comment by roll** [comment]
@cschloer 
I don't know what this line does TBH (it was a quick feature we added). It looks like some heuristic but a comment on what exactly would not hurt 

I think we need to fix it

**Comment by adyork** [comment]
I added the original data file to usecases here: https://github.com/BCODMO/frictionless-usecases/tree/master/usecases/786028_abund/orig

But basically this is a good example of what we are doing when data needs to be unpivoted.  We have to first load multiple header rows in the load step to have one set of field names.

In this case we need to load data from header rows 1-4 in the original file.  All the columns loaded correctly except this one cell that is missing the 2. It should have loaded as `135 C 182 2` not `135 C 182`
![image](https://user-images.githubusercontent.com/9537357/71732165-90b18c80-2e14-11ea-8ebd-04759bdab13e.png)
* screenshot shows [original Excel data](https://github.com/BCODMO/frictionless-usecases/blob/master/usecases/786028_abund/orig/Pvent_P&S_135_supptable1_submit.xlsx?raw=true) below and above shows the field names loaded with setting header rows 1-4.

We then parse that (e.g. `135 C 182 2` ) apart into actual data columns in unpivot in a later step.  Which has some other issues related to having space as the delimiter, but I am putting together a clear example of how we are using unpivot to explain why that is an issue for us.  That is a pending issue.

**Comment by roll** [comment]
@cschloer 
Transferring to the `tabulator` repo?

**Comment by cschloer** [comment]
https://github.com/frictionlessdata/tabulator-py/issues/292
