### ISSUE TITLE
Tabulator header parameter

### ISSUE THREAD

**Issue by cschloer** [BCODMO/frictionless-usecases#36]
To follow up while you are looking into https://github.com/BCODMO/frictionless-usecases/issues/35

We would like the ability to specify what value is used as the separator in the `Headers` parameter. Currently if you have multiple headers they are separated by a space. It would be great if there was a new parameter into tabulator that allowed you to specify that separator.

**Comment by roll** [comment]
@cschloer 
It sounds good the feature is raw as I mentioned in #35 

So polishing it makes sense

**Comment by adyork** [comment]
Yes, as I mentioned in #35, having space as a delimiter for combined header rows makes later parsing in unpivot difficult.

**Comment by roll** [comment]
@cschloer 
Also transferring to the `tabulator` repo?

**Comment by cschloer** [comment]
https://github.com/frictionlessdata/tabulator-py/issues/291
