### ISSUE TITLE
Can't set type for "Temperature (24)" column

### ISSUE THREAD

**Issue by adyork** [BCODMO/frictionless-usecases#9]
Encountered error when trying to set type for a column that included parentheses in the field name.

See usecase [754644_Carpenter2018_physical_data]( https://github.com/BCODMO/frictionless-usecases/tree/master/usecases/754644_Carpenter2018_physical_data)

Error message from pipeline-web tool:

```
    INFO :RESULTS:

    INFO :FAILURE: ./40f79ec8-5575-11e9-ae8b-0242ac110002/missing-data-identifiers-excel

    ERROR log from processor set_types:

    +--------

    | Traceback (most recent call last):

    | File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/set_types.py", line 26, in <module>

    | spew_flow(flow(ctx.parameters), ctx)

    | File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/utilities/flow_utils.py", line 46, in spew_flow

    | datastream = flow.datastream()

    | File "/usr/local/lib/python3.6/site-packages/dataflows/base/flow.py", line 18, in datastream

    | return self._chain(ds)._process()

    | File "/usr/local/lib/python3.6/site-packages/dataflows/base/datastream_processor.py", line 42, in _process

    | datastream = self.source._process()

    | File "/usr/local/lib/python3.6/site-packages/dataflows/base/datastream_processor.py", line 42, in _process

    | datastream = self.source._process()

    | File "/usr/local/lib/python3.6/site-packages/dataflows/base/datastream_processor.py", line 42, in _process

    | datastream = self.source._process()

    | File "/usr/local/lib/python3.6/site-packages/dataflows/base/datastream_processor.py", line 46, in _process

    | self.datapackage = self.process_datapackage(self.datapackage)

    | File "/usr/local/lib/python3.6/site-packages/dataflows/processors/set_type.py", line 37, in process_datapackage

    | assert added, 'Failed to find field {} in schema'.format(self.name)

    | AssertionError: Failed to find field re.compile('^Temperature (24h)$') in schema

```

**Comment by adyork** [comment]
I did a little testing with a simple pipeline-spec.yaml and csv purely with datapackage-pipelines, not our web tool.  Ran them with dpp on command line.

test.csv
```
test_id,temperature,temperature (24h)
1,32,23
2,,26
3,30,21
```

This gave me an error in set_type
```
test:
  description: "test set_types with colname with parentheses"
  pipeline:
  
  - run: load
    parameters:
      from: 'test.csv'
      name: data
      format: csv    

  - run: set_types
    parameters:
        resources: data
        types:
          temperature (24h):
              type: integer

  - run: dump.to_path
    parameters:
      resources: [data]
      out-path: 'output'
           
  title: test
```
```
./test: FAILURE, processed 3 rows
INFO    :RESULTS:
INFO    :FAILURE: ./test 
ERROR log from processor set_types:
+--------
| Traceback (most recent call last):
|   File "/home/adyork/.local/lib/python3.6/site-packages/datapackage_pipelines/specs/../lib/set_types.py", line 26, in <module>
|     spew_flow(flow(ctx.parameters), ctx)
|   File "/home/adyork/.local/lib/python3.6/site-packages/datapackage_pipelines/utilities/flow_utils.py", line 46, in spew_flow
|     datastream = flow.datastream()
|   File "/home/adyork/.local/lib/python3.6/site-packages/dataflows/base/flow.py", line 18, in datastream
|     return self._chain(ds)._process()
|   File "/home/adyork/.local/lib/python3.6/site-packages/dataflows/base/datastream_processor.py", line 46, in _process
|     self.datapackage = self.process_datapackage(self.datapackage)
|   File "/home/adyork/.local/lib/python3.6/site-packages/dataflows/processors/set_type.py", line 37, in process_datapackage
|     assert added, 'Failed to find field {} in schema'.format(self.name)
| AssertionError: Failed to find field re.compile('^temperature (24h)$') in schema

```

This worked if I escaped the parentheses in the field name:

```
test:
  description: "test set_types with colname with parentheses"
  pipeline:
  
  - run: load
    parameters:
      from: 'test.csv'
      name: data
      format: csv    

  - run: set_types
    parameters:
        resources: data
        types:
          temperature \(24h\):
              type: integer

  - run: dump.to_path
    parameters:
      resources: [data]
      out-path: 'output'
           
  title: test
```
```
./test: SUCCESS, processed 3 rows
INFO    :RESULTS:
INFO    :SUCCESS: ./test {'bytes': 810, 'count_of_rows': 3, 'dataset_name': '_', 'hash': '6dfd26f462a70e8c282e06d242feb775'}
```

Escaping parentheses in column names is a solution if constructing pipelines by hand, but users have to know to do it.  It is an added layer of complexity when trying to construct steps in a more automated manner. 

@cschloer can you describe to the @BCODMO/frictionlessdata-pilot-project how this problem affects our web tool?

**Comment by cschloer** [comment]
So this is happening specifically for set_types because of set_types looking for a regular expression (`field name is either simply the name of a field, or a regular expression matching multiple fields.` - https://github.com/frictionlessdata/datapackage-pipelines#set_types). A few things regarding that:

1. This is different from all other processors that deal with fields. All other ones take in a list of fields and values. So while currently the set_types data structure looks like:
```
{
  ...,
  fields: {
    field1: string,
    field2: string,
    field3: number,
  },
}
```
To fit more in line with the rest of the processors it should look like:
```
{
  ...,
  fields: [
    { name: field1, type: string },
    { name: field2, type: string },
    { name: field3, type: number },
  ],
}
```
The above change would lose the ability to match multiple fields, but that could be fixed easily by allowing the name key to take in a list (and rename it names). This is obviously a design choice on your (Frictionless') end, but I think it makes more sense to be consistent across processors. And then you don't have the issue of needing to escape fields that have regular expresions

**Comment by lwinfree** [comment]
Hi @adyork! Do you happen to have a link to the web tool so @roll can play with it? (also I'm assuming the 'web tool' is the UI?) I'm going to send him the video of your csvconf talk once it gets posted so he can see it in action, but are there other resources that you could give him so he can get to know your process better? Thanks!

**Comment by roll** [comment]
The `regex` parameter has been added to the `set_types` processor:
- https://github.com/frictionlessdata/datapackage-pipelines#set_types

```yml
  - run: set_types
    parameters:
        resources: data
        regex: false
        types:
          temperature (24h):
              type: integer
```

So now, it's possible to interpret field names as strings

**Comment by cschloer** [comment]
Is it possible to have this same parameter for delete_fields? I believe delete_fields also takes in regex (though the documentation does not say this). @roll

**Comment by roll** [comment]
@cschloer 
I've created an issue for it - #16

**Comment by adyork** [comment]
Great! It seems this got resolved.  I was able to both set types and rename the fields in our pipeline ui.

@cschloer would you consider this case closed or are there any lingering issues you know of?

[pipeline-spec.yaml.txt](https://github.com/BCODMO/frictionless-usecases/files/3273197/pipeline-spec.yaml.txt)
loaded (as strings, () in names)
![image](https://user-images.githubusercontent.com/9537357/59215594-9cdbb100-8b87-11e9-8668-99d34a050805.png)
After set types and renaming:
![image](https://user-images.githubusercontent.com/9537357/59215572-92211c00-8b87-11e9-9f50-6868cd5db653.png)

@lwinfree I just saw your request for materials about our ui for the pipelines other than my talk.  I don't think we really have anything prepared at this point but I will shoot you something when we do.
